trigger: none

pool:
 name: Alpha-pool

steps:
  - script: echo hello world
    displayName: "print name"
  - script: |
      echo this is pipeline running using $(Agent.PoolName)
    displayName: "running pipelines"

